#!/bin/bash

for net in fc_3 fc_4
do
	echo Evaluating network ${net}...
	for spec in `ls preliminary_evaluation_test_cases/${net}`
	do
		python code/verifier.py --net ${net} --spec preliminary_evaluation_test_cases/${net}/${spec}
	done
done
