#!/bin/bash

for net in fc_3 fc_4 fc_5 fc_6
do
	echo Evaluating network ${net}...
	for spec in `ls test_cases/${net}`
	do
		python code/verifier.py --net ${net} --spec test_cases/${net}/${spec}
	done
done
